CREATE TABLE SHIPWRECK(
  ID INT AUTO_INCREMENT,
  NAME VARCHAR(255),
  DESCRIPTION VARCHAR(2000),
  CONDITION VARCHAR(255),
  DEPTH INT,
  LATITUDE DOUBLE,
  LONGTITUDE DOUBLE,
  YEAR_DISCOVERED INT
);